language: java
jdk: oraclejdk8
deploy:
  provider: gae
  keyfile: client-secret.json 
  project: conv3rt3r
before_install:
- openssl aes-256-cbc -K $encrypted_55118ca32fc7_key -iv $encrypted_55118ca32fc7_iv
  -in client-secret.json.enc -out client-secret.json -d
