language: java
jdk: openjdk8

before_install:
- openssl aes-256-cbc -K $encrypted_55118ca32fc7_key -iv $encrypted_55118ca32fc7_iv
  -in client-secret.json.enc -out client-secret.json -d
- if [ ! -d $HOME/google-cloud-sdk ]; then  
    curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file client-secret.json --project=conv3rt3r
install:
- gcloud components install app-engine-java
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
config: "./src/main/webapp/WEB-INF/appengine-web.xml"
script:
- ./mvnw appengine:deploy -DskipTests
# deploy:
#   provider: gae
#   keyfile: client-secret.json
#   project: conv3rt3r


