name: Frontend Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: eu-west-1

    - name: Read API URL from S3
      run: |
        aws s3 cp s3://p11h-converter-frontend-config/api-url.txt ./api-url.txt
        cat api-url.txt

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build frontend
      run: |
        echo "VITE_API_URL=$(cat ../api-url.txt)" > .env.production
        npm run build

    - name: Deploy to S3
      run: aws s3 sync dist/ s3://p11h-converter --delete 